const server="http://127.0.0.1:8000/"
export const loginApi=server+"api/login"
export const logoutApi=server+"api/logout"
export const createRoomApi=server+"api/room/create"
export const showRoomApi=server+"api/room/show"
export const joinRoomApi=server+"api/room/join"
export const updateApp=server+"api/app/update"